# Generated by Django 6.0.5 on 2026-05-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("innoapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("summary", models.TextField()),
                ("body", models.TextField()),
                ("day", models.CharField(blank=True, max_length=8)),
                ("month", models.CharField(blank=True, max_length=32)),
                ("date_text", models.CharField(blank=True, max_length=80)),
                ("location", models.CharField(blank=True, max_length=180)),
                ("info_label", models.CharField(default="Info:", max_length=80)),
                ("info", models.CharField(blank=True, max_length=180)),
                ("button_text", models.CharField(default="Learn More", max_length=80)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="media/events/"),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="HeroVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("video", models.FileField(blank=True, upload_to="videos/hero/")),
                (
                    "poster",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/hero-posters/"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("role", models.CharField(blank=True, max_length=160)),
                ("quote", models.TextField()),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("whatsapp_url", models.URLField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/testimonials/"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
