# Generated by Django 6.0.5 on 2026-05-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("innoapp", "0002_eventinsight_herovideo_testimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("phone", models.CharField(blank=True, max_length=80)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(default="Floating Contact Form", max_length=80),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("subtitle", models.CharField(blank=True, max_length=220)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(default="Featured", max_length=80)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/gallery/"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
